FROM viapath/snappy_ngstools:flatdog
MAINTAINER David Brawand <dbrawand@nhs.net>
ENV HOME /root

## bcl2fastq2 2.17

ENV TMP /tmp
ENV SOURCE ${TMP}/bcl2fastq
ENV BUILD ${TMP}/bcl2fastq2-v2.17.1.x-build
ENV INSTALL_DIR /usr/local/pipeline/bcl2fastq2

RUN cd ${TMP} && \
    wget ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/software/bcl2fastq/bcl2fastq2-v2.17.1.14.tar.zip

RUN cd ${TMP} && \
    unzip bcl2fastq2-v2.17.1.14.tar.zip && \
    tar xvzf bcl2fastq2-v2.17.1.14.tar.gz

RUN apt-get update && apt-get install -y libboost-all-dev

RUN mkdir -p ${BUILD} && \
    cd ${BUILD} && \
    ${SOURCE}/src/configure --prefix=${INSTALL_DIR}

# RUN cd ${BUILD} && \
#     make && make install

# RUN sed -i '$aPATH=${PATH}:${INSTALL_DIR}' /home/snappy/.bashrc && \
#     chmod -R 755 ${INSTALL_DIR} && \
#     chown -R snappy:snappy /usr/local/pipeline && \
#     rm -rf /tmp/*

CMD ["/bin/bash"]
